# logging.level: debug

filebeat.config.modules:
  enabled: true
  path: /usr/share/filebeat/modules.d/*.yml

filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

- type: netflow
  max_message_size: 10KiB
  host: "0.0.0.0:2056"
  protocols: [ v5, v9, ipfix ]
  expiration_timeout: 30m
  queue_size: 8192
  detect_sequence_reset: true


# filebeat.inputs:
# - type: syslog
#   format: rfc3164
#   protocol.udp:
  #   host: "localhost:9528"

# - type: udp
#   max_message_size: 10KiB
  # tags: ["json"]
  #   host: "localhost:8080"

# - type: udp
#   enabled: true
#   # host: "0.0.0.0:2055"  # Porta padrão para NetFlow, altere conforme necessário
#   fields:
#   source: "netflow"
#   fields_under_root: true


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT} 

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}
