filebeat.config.modules:
  enabled: true
  path: /usr/share/filebeat/modules.d/*.yml

filebeat.inputs:
- type: syslog
  format: rfc3164
  protocol.udp:
  #   host: "localhost:9528"
- type: udp
  max_message_size: 10KiB
  # tags: ["json"]
  #   host: "localhost:8080"

# filebeat.inputs:
# - type: filestream
#   id: default-filestream
#   paths:
#     - ingest_data/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD} 

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}
