filebeat.config.modules:
  enabled: true
  path: /usr/share/filebeat/modules.d/*.yml

filebeat.inputs:
- type: log
  #id: logstash-filestream
  paths:
    - /usr/share/filebeat/mylog/*log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  setup.kibana.ssl.verification_mode: "none"
  setup.kibana.ssl.certificate_authorities: "certs/ca/ca.crt"

output.logstash:
  hosts: [logstash01:5044]
  #username: ${ELASTIC_USER}
  #password: ${ELASTIC_PASSWORD}
  #ssl.enabled: true
  #ssl.certificate_authorities: "certs/ca/ca.crt"
  